name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: gemachistesfaye
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23A855F7&color_dots=%23161B22,%230E4429,%2300651D,%2326A641,%2339D353

      - name: Commit Generated Files
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist"
          message: "chore: update contribution snake animation"
